package com.monetware.model.collect;

import java.util.Date;

public class CollectProxyHost {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column collect_proxy_host.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column collect_proxy_host.ip
	 * @mbg.generated
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column collect_proxy_host.port
	 * @mbg.generated
	 */
	private Integer port;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column collect_proxy_host.last_use_time
	 * @mbg.generated
	 */
	private Long lastUseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column collect_proxy_host.first_use_time
	 * @mbg.generated
	 */
	private Long firstUseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column collect_proxy_host.score
	 * @mbg.generated
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column collect_proxy_host.is_use_now
	 * @mbg.generated
	 */
	private Integer isUseNow;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column collect_proxy_host.id
	 * @return  the value of collect_proxy_host.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column collect_proxy_host.id
	 * @param id  the value for collect_proxy_host.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column collect_proxy_host.ip
	 * @return  the value of collect_proxy_host.ip
	 * @mbg.generated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column collect_proxy_host.ip
	 * @param ip  the value for collect_proxy_host.ip
	 * @mbg.generated
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column collect_proxy_host.port
	 * @return  the value of collect_proxy_host.port
	 * @mbg.generated
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column collect_proxy_host.port
	 * @param port  the value for collect_proxy_host.port
	 * @mbg.generated
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column collect_proxy_host.last_use_time
	 * @return  the value of collect_proxy_host.last_use_time
	 * @mbg.generated
	 */
	
	public Integer getScore() {
		return score;
	}

	public Long getLastUseTime() {
		return lastUseTime;
	}

	public void setLastUseTime(Long lastUseTime) {
		this.lastUseTime = lastUseTime;
	}

	public Long getFirstUseTime() {
		return firstUseTime;
	}

	public void setFirstUseTime(Long firstUseTime) {
		this.firstUseTime = firstUseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column collect_proxy_host.score
	 * @param score  the value for collect_proxy_host.score
	 * @mbg.generated
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column collect_proxy_host.is_use_now
	 * @return  the value of collect_proxy_host.is_use_now
	 * @mbg.generated
	 */
	public Integer getIsUseNow() {
		return isUseNow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column collect_proxy_host.is_use_now
	 * @param isUseNow  the value for collect_proxy_host.is_use_now
	 * @mbg.generated
	 */
	public void setIsUseNow(Integer isUseNow) {
		this.isUseNow = isUseNow;
	}
}