package com.monetware.model.collect;

import java.util.Date;
import java.util.List;

public class CollectTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.template_level
     *
     * @mbg.generated
     */
    private Integer templateLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.interval
     *
     * @mbg.generated
     */
    private Integer interval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.depth
     *
     * @mbg.generated
     */
    private Integer depth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.next_url_xpath
     *
     * @mbg.generated
     */
    private String nextUrlXpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.content_url_xpath
     *
     * @mbg.generated
     */
    private String contentUrlXpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.list_url_regex
     *
     * @mbg.generated
     */
    private String listUrlRegex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.content_url_regex
     *
     * @mbg.generated
     */
    private String contentUrlRegex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.entry_urls
     *
     * @mbg.generated
     */
//    private String entryUrls;


    //入口url
    private List<String> entryUrls;

    //方便数据库存储多组url
    private String entryUrlsStr;

    private String domain;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.cookie
     *
     * @mbg.generated
     */
    private String cookie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_template.fields
     *
     * @mbg.generated
     */


    //具体页抓取信息的xpath语句
    private List<CollectTemplateField> fields;

    //方便数据库存储fields
    private String fieldsStr;




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.id
     *
     * @return the value of collect_template.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.id
     *
     * @param id the value for collect_template.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.name
     *
     * @return the value of collect_template.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.name
     *
     * @param name the value for collect_template.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.template_level
     *
     * @return the value of collect_template.template_level
     *
     * @mbg.generated
     */
    public Integer getTemplateLevel() {
        return templateLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.template_level
     *
     * @param templateLevel the value for collect_template.template_level
     *
     * @mbg.generated
     */
    public void setTemplateLevel(Integer templateLevel) {
        this.templateLevel = templateLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.type
     *
     * @return the value of collect_template.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.type
     *
     * @param type the value for collect_template.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.create_time
     *
     * @return the value of collect_template.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.create_time
     *
     * @param createTime the value for collect_template.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.create_user
     *
     * @return the value of collect_template.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.create_user
     *
     * @param createUser the value for collect_template.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.interval
     *
     * @return the value of collect_template.interval
     *
     * @mbg.generated
     */
    public Integer getInterval() {
        return interval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.interval
     *
     * @param interval the value for collect_template.interval
     *
     * @mbg.generated
     */
    public void setInterval(Integer interval) {
        this.interval = interval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.depth
     *
     * @return the value of collect_template.depth
     *
     * @mbg.generated
     */
    public Integer getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.depth
     *
     * @param depth the value for collect_template.depth
     *
     * @mbg.generated
     */
    public void setDepth(Integer depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.next_url_xpath
     *
     * @return the value of collect_template.next_url_xpath
     *
     * @mbg.generated
     */
    public String getNextUrlXpath() {
        return nextUrlXpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.next_url_xpath
     *
     * @param nextUrlXpath the value for collect_template.next_url_xpath
     *
     * @mbg.generated
     */
    public void setNextUrlXpath(String nextUrlXpath) {
        this.nextUrlXpath = nextUrlXpath == null ? null : nextUrlXpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.content_url_xpath
     *
     * @return the value of collect_template.content_url_xpath
     *
     * @mbg.generated
     */
    public String getContentUrlXpath() {
        return contentUrlXpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.content_url_xpath
     *
     * @param contentUrlXpath the value for collect_template.content_url_xpath
     *
     * @mbg.generated
     */
    public void setContentUrlXpath(String contentUrlXpath) {
        this.contentUrlXpath = contentUrlXpath == null ? null : contentUrlXpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.list_url_regex
     *
     * @return the value of collect_template.list_url_regex
     *
     * @mbg.generated
     */
    public String getListUrlRegex() {
        return listUrlRegex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.list_url_regex
     *
     * @param listUrlRegex the value for collect_template.list_url_regex
     *
     * @mbg.generated
     */
    public void setListUrlRegex(String listUrlRegex) {
        this.listUrlRegex = listUrlRegex == null ? null : listUrlRegex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.content_url_regex
     *
     * @return the value of collect_template.content_url_regex
     *
     * @mbg.generated
     */
    public String getContentUrlRegex() {
        return contentUrlRegex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.content_url_regex
     *
     * @param contentUrlRegex the value for collect_template.content_url_regex
     *
     * @mbg.generated
     */
    public void setContentUrlRegex(String contentUrlRegex) {
        this.contentUrlRegex = contentUrlRegex == null ? null : contentUrlRegex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.description
     *
     * @return the value of collect_template.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.description
     *
     * @param description the value for collect_template.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.entry_urls
     *
     * @return the value of collect_template.entry_urls
     *
     * @mbg.generated
     */
    public String getEntryUrlsStr() {
        return entryUrlsStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.entry_urls
     *
     * @param entryUrls the value for collect_template.entry_urls
     *
     * @mbg.generated
     */
    public void setEntryUrlsStr(String entryUrlsStr) {
        this.entryUrlsStr = entryUrlsStr == null ? null : entryUrlsStr.trim();
    }


    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.cookie
     *
     * @return the value of collect_template.cookie
     *
     * @mbg.generated
     */
    public String getCookie() {
        return cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.cookie
     *
     * @param cookie the value for collect_template.cookie
     *
     * @mbg.generated
     */
    public void setCookie(String cookie) {
        this.cookie = cookie == null ? null : cookie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_template.fields
     *
     * @return the value of collect_template.fields
     *
     * @mbg.generated
     */
    public String getFieldsStr() {
        return fieldsStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_template.fields
     *
     * @param fields the value for collect_template.fields
     *
     * @mbg.generated
     */

    public void setFieldsStr(String fieldsStr) {
        this.fieldsStr = fieldsStr == null ? null : fieldsStr.trim();
    }

    public List<String> getEntryUrls() {
        return entryUrls;
    }

    public void setEntryUrls(List<String> entryUrls) {
        this.entryUrls = entryUrls;
    }

    public List<CollectTemplateField> getFields() {
        return fields;
    }

    public void setFields(List<CollectTemplateField> fields) {
        this.fields = fields;
    }
}