package com.monetware.model.analysis;

import java.util.Date;

public class AnalysisProjectWord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_words_1.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_words_1.word
     *
     * @mbg.generated
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_words_1.nature
     *
     * @mbg.generated
     */
    private String nature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_words_1.frequency
     *
     * @mbg.generated
     */
    private Integer frequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_words_1.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_words_1.id
     *
     * @return the value of analysis_project_words_1.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_words_1.id
     *
     * @param id the value for analysis_project_words_1.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_words_1.word
     *
     * @return the value of analysis_project_words_1.word
     *
     * @mbg.generated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_words_1.word
     *
     * @param word the value for analysis_project_words_1.word
     *
     * @mbg.generated
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_words_1.nature
     *
     * @return the value of analysis_project_words_1.nature
     *
     * @mbg.generated
     */
    public String getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_words_1.nature
     *
     * @param nature the value for analysis_project_words_1.nature
     *
     * @mbg.generated
     */
    public void setNature(String nature) {
        this.nature = nature == null ? null : nature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_words_1.frequency
     *
     * @return the value of analysis_project_words_1.frequency
     *
     * @mbg.generated
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_words_1.frequency
     *
     * @param frequency the value for analysis_project_words_1.frequency
     *
     * @mbg.generated
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_words_1.create_time
     *
     * @return the value of analysis_project_words_1.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_words_1.create_time
     *
     * @param createTime the value for analysis_project_words_1.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}