package com.monetware.model.analysis;

import java.util.Date;

public class AnalysisSentimeWord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_sentime_word.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_sentime_word.dictionary_id
     *
     * @mbg.generated
     */
    private Long dictionaryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_sentime_word.word
     *
     * @mbg.generated
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_sentime_word.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_sentime_word.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_sentime_word.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_sentime_word.id
     *
     * @return the value of analysis_sentime_word.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_sentime_word.id
     *
     * @param id the value for analysis_sentime_word.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_sentime_word.dictionary_id
     *
     * @return the value of analysis_sentime_word.dictionary_id
     *
     * @mbg.generated
     */
    public Long getDictionaryId() {
        return dictionaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_sentime_word.dictionary_id
     *
     * @param dictionaryId the value for analysis_sentime_word.dictionary_id
     *
     * @mbg.generated
     */
    public void setDictionaryId(Long dictionaryId) {
        this.dictionaryId = dictionaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_sentime_word.word
     *
     * @return the value of analysis_sentime_word.word
     *
     * @mbg.generated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_sentime_word.word
     *
     * @param word the value for analysis_sentime_word.word
     *
     * @mbg.generated
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_sentime_word.score
     *
     * @return the value of analysis_sentime_word.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_sentime_word.score
     *
     * @param score the value for analysis_sentime_word.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_sentime_word.create_user
     *
     * @return the value of analysis_sentime_word.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_sentime_word.create_user
     *
     * @param createUser the value for analysis_sentime_word.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_sentime_word.create_time
     *
     * @return the value of analysis_sentime_word.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_sentime_word.create_time
     *
     * @param createTime the value for analysis_sentime_word.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}