package com.monetware.model.analysis;

import java.util.Date;

public class AnalysisProjectClassifyTraining {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_classify_training.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_classify_training.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_classify_training.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_classify_training.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_classify_training.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_classify_training.id
     *
     * @return the value of analysis_project_classify_training.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_classify_training.id
     *
     * @param id the value for analysis_project_classify_training.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_classify_training.category_name
     *
     * @return the value of analysis_project_classify_training.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_classify_training.category_name
     *
     * @param categoryName the value for analysis_project_classify_training.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_classify_training.create_time
     *
     * @return the value of analysis_project_classify_training.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_classify_training.create_time
     *
     * @param createTime the value for analysis_project_classify_training.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_classify_training.create_user
     *
     * @return the value of analysis_project_classify_training.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_classify_training.create_user
     *
     * @param createUser the value for analysis_project_classify_training.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_classify_training.text
     *
     * @return the value of analysis_project_classify_training.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_classify_training.text
     *
     * @param text the value for analysis_project_classify_training.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}