package com.monetware.model.analysis;

import java.util.Date;

public class AnalysisProjectCluste {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_cluste.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_cluste.project_id
     *
     * @mbg.generated
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_cluste.text_no
     *
     * @mbg.generated
     */
    private Long textNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_cluste.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_cluste.cluster_name
     *
     * @mbg.generated
     */
    private String clusterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_cluste.id
     *
     * @return the value of analysis_project_cluste.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_cluste.id
     *
     * @param id the value for analysis_project_cluste.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_cluste.project_id
     *
     * @return the value of analysis_project_cluste.project_id
     *
     * @mbg.generated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_cluste.project_id
     *
     * @param projectId the value for analysis_project_cluste.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_cluste.text_no
     *
     * @return the value of analysis_project_cluste.text_no
     *
     * @mbg.generated
     */
    public Long getTextNo() {
        return textNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_cluste.text_no
     *
     * @param textNo the value for analysis_project_cluste.text_no
     *
     * @mbg.generated
     */
    public void setTextNo(Long textNo) {
        this.textNo = textNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_cluste.create_time
     *
     * @return the value of analysis_project_cluste.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_cluste.create_time
     *
     * @param createTime the value for analysis_project_cluste.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_cluste.cluster_name
     *
     * @return the value of analysis_project_cluste.cluster_name
     *
     * @mbg.generated
     */
    public String getClusterName() {
        return clusterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_cluste.cluster_name
     *
     * @param clusterName the value for analysis_project_cluste.cluster_name
     *
     * @mbg.generated
     */
    public void setClusterName(String clusterName) {
        this.clusterName = clusterName == null ? null : clusterName.trim();
    }
}