package com.monetware.model.analysis;

import java.util.Date;

public class AnalysisProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.describle
     *
     * @mbg.generated
     */
    private String describle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.textlibrary_id
     *
     * @mbg.generated
     */
    private Long textlibraryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.segment_status
     *
     * @mbg.generated
     */
    private Integer segmentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.cluste_fields
     *
     * @mbg.generated
     */
    private String clusteFields;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.cluste_algorithm
     *
     * @mbg.generated
     */
    private Integer clusteAlgorithm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.cluste_count
     *
     * @mbg.generated
     */
    private Integer clusteCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.cluste_status
     *
     * @mbg.generated
     */
    private Integer clusteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.cluste_start_time
     *
     * @mbg.generated
     */
    private Date clusteStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.cluste_end_time
     *
     * @mbg.generated
     */
    private Date clusteEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.classify_status
     *
     * @mbg.generated
     */
    private Integer classifyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.classify_fields
     *
     * @mbg.generated
     */
    private String classifyFields;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.classify_start_time
     *
     * @mbg.generated
     */
    private Date classifyStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.classify_end_time
     *
     * @mbg.generated
     */
    private Date classifyEndTime;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.sentime_status
     *
     * @mbg.generated
     */
    private Integer sentimeStatus;

    
    
    private String sentimeFields;
    
    
    
    private String sentimeWords;
    
    
    
    private Date sentimeStartTime;
    
    
    private Date sentimeEndTime;
    
    
    
    
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.segment_type
     *
     * @mbg.generated
     */
    private String segmentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.segment_column
     *
     * @mbg.generated
     */
    private String segmentColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.classify_categories
     *
     * @mbg.generated
     */
    private String classifyCategories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project.classify_model
     *
     * @mbg.generated
     */
    private String classifyModel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.id
     *
     * @return the value of analysis_project.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.id
     *
     * @param id the value for analysis_project.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.name
     *
     * @return the value of analysis_project.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.name
     *
     * @param name the value for analysis_project.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.describle
     *
     * @return the value of analysis_project.describle
     *
     * @mbg.generated
     */
    public String getDescrible() {
        return describle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.describle
     *
     * @param describle the value for analysis_project.describle
     *
     * @mbg.generated
     */
    public void setDescrible(String describle) {
        this.describle = describle == null ? null : describle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.textlibrary_id
     *
     * @return the value of analysis_project.textlibrary_id
     *
     * @mbg.generated
     */
    public Long getTextlibraryId() {
        return textlibraryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.textlibrary_id
     *
     * @param textlibraryId the value for analysis_project.textlibrary_id
     *
     * @mbg.generated
     */
    public void setTextlibraryId(Long textlibraryId) {
        this.textlibraryId = textlibraryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.create_user
     *
     * @return the value of analysis_project.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.create_user
     *
     * @param createUser the value for analysis_project.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.create_time
     *
     * @return the value of analysis_project.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.create_time
     *
     * @param createTime the value for analysis_project.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.segment_status
     *
     * @return the value of analysis_project.segment_status
     *
     * @mbg.generated
     */
    public Integer getSegmentStatus() {
        return segmentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.segment_status
     *
     * @param segmentStatus the value for analysis_project.segment_status
     *
     * @mbg.generated
     */
    public void setSegmentStatus(Integer segmentStatus) {
        this.segmentStatus = segmentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.cluste_fields
     *
     * @return the value of analysis_project.cluste_fields
     *
     * @mbg.generated
     */
    public String getClusteFields() {
        return clusteFields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.cluste_fields
     *
     * @param clusteFields the value for analysis_project.cluste_fields
     *
     * @mbg.generated
     */
    public void setClusteFields(String clusteFields) {
        this.clusteFields = clusteFields == null ? null : clusteFields.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.cluste_algorithm
     *
     * @return the value of analysis_project.cluste_algorithm
     *
     * @mbg.generated
     */
    public Integer getClusteAlgorithm() {
        return clusteAlgorithm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.cluste_algorithm
     *
     * @param clusteAlgorithm the value for analysis_project.cluste_algorithm
     *
     * @mbg.generated
     */
    public void setClusteAlgorithm(Integer clusteAlgorithm) {
        this.clusteAlgorithm = clusteAlgorithm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.cluste_count
     *
     * @return the value of analysis_project.cluste_count
     *
     * @mbg.generated
     */
    public Integer getClusteCount() {
        return clusteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.cluste_count
     *
     * @param clusteCount the value for analysis_project.cluste_count
     *
     * @mbg.generated
     */
    public void setClusteCount(Integer clusteCount) {
        this.clusteCount = clusteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.cluste_status
     *
     * @return the value of analysis_project.cluste_status
     *
     * @mbg.generated
     */
    public Integer getClusteStatus() {
        return clusteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.cluste_status
     *
     * @param clusteStatus the value for analysis_project.cluste_status
     *
     * @mbg.generated
     */
    public void setClusteStatus(Integer clusteStatus) {
        this.clusteStatus = clusteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.cluste_start_time
     *
     * @return the value of analysis_project.cluste_start_time
     *
     * @mbg.generated
     */
    public Date getClusteStartTime() {
        return clusteStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.cluste_start_time
     *
     * @param clusteStartTime the value for analysis_project.cluste_start_time
     *
     * @mbg.generated
     */
    public void setClusteStartTime(Date clusteStartTime) {
        this.clusteStartTime = clusteStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.cluste_end_time
     *
     * @return the value of analysis_project.cluste_end_time
     *
     * @mbg.generated
     */
    public Date getClusteEndTime() {
        return clusteEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.cluste_end_time
     *
     * @param clusteEndTime the value for analysis_project.cluste_end_time
     *
     * @mbg.generated
     */
    public void setClusteEndTime(Date clusteEndTime) {
        this.clusteEndTime = clusteEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.classify_status
     *
     * @return the value of analysis_project.classify_status
     *
     * @mbg.generated
     */
    public Integer getClassifyStatus() {
        return classifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.classify_status
     *
     * @param classifyStatus the value for analysis_project.classify_status
     *
     * @mbg.generated
     */
    public void setClassifyStatus(Integer classifyStatus) {
        this.classifyStatus = classifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.classify_fields
     *
     * @return the value of analysis_project.classify_fields
     *
     * @mbg.generated
     */
    public String getClassifyFields() {
        return classifyFields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.classify_fields
     *
     * @param classifyFields the value for analysis_project.classify_fields
     *
     * @mbg.generated
     */
    public void setClassifyFields(String classifyFields) {
        this.classifyFields = classifyFields == null ? null : classifyFields.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.classify_start_time
     *
     * @return the value of analysis_project.classify_start_time
     *
     * @mbg.generated
     */
    public Date getClassifyStartTime() {
        return classifyStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.classify_start_time
     *
     * @param classifyStartTime the value for analysis_project.classify_start_time
     *
     * @mbg.generated
     */
    public void setClassifyStartTime(Date classifyStartTime) {
        this.classifyStartTime = classifyStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.classify_end_time
     *
     * @return the value of analysis_project.classify_end_time
     *
     * @mbg.generated
     */
    public Date getClassifyEndTime() {
        return classifyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.classify_end_time
     *
     * @param classifyEndTime the value for analysis_project.classify_end_time
     *
     * @mbg.generated
     */
    public void setClassifyEndTime(Date classifyEndTime) {
        this.classifyEndTime = classifyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.sentime_status
     *
     * @return the value of analysis_project.sentime_status
     *
     * @mbg.generated
     */
    public Integer getSentimeStatus() {
        return sentimeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.sentime_status
     *
     * @param sentimeStatus the value for analysis_project.sentime_status
     *
     * @mbg.generated
     */
    public void setSentimeStatus(Integer sentimeStatus) {
        this.sentimeStatus = sentimeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.segment_type
     *
     * @return the value of analysis_project.segment_type
     *
     * @mbg.generated
     */
    public String getSegmentType() {
        return segmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.segment_type
     *
     * @param segmentType the value for analysis_project.segment_type
     *
     * @mbg.generated
     */
    public void setSegmentType(String segmentType) {
        this.segmentType = segmentType == null ? null : segmentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.segment_column
     *
     * @return the value of analysis_project.segment_column
     *
     * @mbg.generated
     */
    public String getSegmentColumn() {
        return segmentColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.segment_column
     *
     * @param segmentColumn the value for analysis_project.segment_column
     *
     * @mbg.generated
     */
    public void setSegmentColumn(String segmentColumn) {
        this.segmentColumn = segmentColumn == null ? null : segmentColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.classify_categories
     *
     * @return the value of analysis_project.classify_categories
     *
     * @mbg.generated
     */
    public String getClassifyCategories() {
        return classifyCategories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.classify_categories
     *
     * @param classifyCategories the value for analysis_project.classify_categories
     *
     * @mbg.generated
     */
    public void setClassifyCategories(String classifyCategories) {
        this.classifyCategories = classifyCategories == null ? null : classifyCategories.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project.classify_model
     *
     * @return the value of analysis_project.classify_model
     *
     * @mbg.generated
     */
    public String getClassifyModel() {
        return classifyModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project.classify_model
     *
     * @param classifyModel the value for analysis_project.classify_model
     *
     * @mbg.generated
     */
    public void setClassifyModel(String classifyModel) {
        this.classifyModel = classifyModel == null ? null : classifyModel.trim();
    }

	public String getSentimeFields() {
		return sentimeFields;
	}

	public void setSentimeFields(String sentimeFields) {
		this.sentimeFields = sentimeFields;
	}

	public String getSentimeWords() {
		return sentimeWords;
	}

	public void setSentimeWords(String sentimeWords) {
		this.sentimeWords = sentimeWords;
	}

	public Date getSentimeStartTime() {
		return sentimeStartTime;
	}

	public void setSentimeStartTime(Date sentimeStartTime) {
		this.sentimeStartTime = sentimeStartTime;
	}

	public Date getSentimeEndTime() {
		return sentimeEndTime;
	}

	public void setSentimeEndTime(Date sentimeEndTime) {
		this.sentimeEndTime = sentimeEndTime;
	}
    
}