package com.monetware.model.analysis;

public class AnalysisSentime {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column analysis_sentime_0.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column analysis_sentime_0.text_info_id
	 * @mbg.generated
	 */
	private Long textInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column analysis_sentime_0.positive_score
	 * @mbg.generated
	 */
	private Integer positiveScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column analysis_sentime_0.negative_score
	 * @mbg.generated
	 */
	private Integer negativeScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column analysis_sentime_0.text
	 * @mbg.generated
	 */
	private String text;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column analysis_sentime_0.id
	 * @return  the value of analysis_sentime_0.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column analysis_sentime_0.id
	 * @param id  the value for analysis_sentime_0.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column analysis_sentime_0.text_info_id
	 * @return  the value of analysis_sentime_0.text_info_id
	 * @mbg.generated
	 */
	public Long getTextInfoId() {
		return textInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column analysis_sentime_0.text_info_id
	 * @param textInfoId  the value for analysis_sentime_0.text_info_id
	 * @mbg.generated
	 */
	public void setTextInfoId(Long textInfoId) {
		this.textInfoId = textInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column analysis_sentime_0.positive_score
	 * @return  the value of analysis_sentime_0.positive_score
	 * @mbg.generated
	 */
	public Integer getPositiveScore() {
		return positiveScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column analysis_sentime_0.positive_score
	 * @param positiveScore  the value for analysis_sentime_0.positive_score
	 * @mbg.generated
	 */
	public void setPositiveScore(Integer positiveScore) {
		this.positiveScore = positiveScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column analysis_sentime_0.negative_score
	 * @return  the value of analysis_sentime_0.negative_score
	 * @mbg.generated
	 */
	public Integer getNegativeScore() {
		return negativeScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column analysis_sentime_0.negative_score
	 * @param negativeScore  the value for analysis_sentime_0.negative_score
	 * @mbg.generated
	 */
	public void setNegativeScore(Integer negativeScore) {
		this.negativeScore = negativeScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column analysis_sentime_0.text
	 * @return  the value of analysis_sentime_0.text
	 * @mbg.generated
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column analysis_sentime_0.text
	 * @param text  the value for analysis_sentime_0.text
	 * @mbg.generated
	 */
	public void setText(String text) {
		this.text = text == null ? null : text.trim();
	}
}