package com.monetware.model.analysis;

import java.util.Date;

public class AnalysisProjectClusteInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_cluste_0.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_cluste_0.cluste_id
     *
     * @mbg.generated
     */
    private Long clusteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_cluste_0.text_info_id
     *
     * @mbg.generated
     */
    private Long textInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_project_cluste_0.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_cluste_0.id
     *
     * @return the value of analysis_project_cluste_0.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_cluste_0.id
     *
     * @param id the value for analysis_project_cluste_0.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_cluste_0.cluste_id
     *
     * @return the value of analysis_project_cluste_0.cluste_id
     *
     * @mbg.generated
     */
    public Long getClusteId() {
        return clusteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_cluste_0.cluste_id
     *
     * @param clusteId the value for analysis_project_cluste_0.cluste_id
     *
     * @mbg.generated
     */
    public void setClusteId(Long clusteId) {
        this.clusteId = clusteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_cluste_0.text_info_id
     *
     * @return the value of analysis_project_cluste_0.text_info_id
     *
     * @mbg.generated
     */
    public Long getTextInfoId() {
        return textInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_cluste_0.text_info_id
     *
     * @param textInfoId the value for analysis_project_cluste_0.text_info_id
     *
     * @mbg.generated
     */
    public void setTextInfoId(Long textInfoId) {
        this.textInfoId = textInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_project_cluste_0.create_time
     *
     * @return the value of analysis_project_cluste_0.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_project_cluste_0.create_time
     *
     * @param createTime the value for analysis_project_cluste_0.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}