package com.monetware.model.analysis;

import java.util.Date;

public class TextLibrary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_textlibrary.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_textlibrary.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_textlibrary.describle
     *
     * @mbg.generated
     */
    private String describle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_textlibrary.fields
     *
     * @mbg.generated
     */
    private String fields;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_textlibrary.line_no
     *
     * @mbg.generated
     */
    private Long lineNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_textlibrary.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    public Integer getCreateUser() {
		return createUser;
	}

	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_textlibrary.filePath
     *
     * @mbg.generated
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_textlibrary.create_time
     *
     * @mbg.generated
     */
    private Date createTime;
    
    
    
    private Integer importStatus;
    
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_textlibrary.id
     *
     * @return the value of analysis_textlibrary.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_textlibrary.id
     *
     * @param id the value for analysis_textlibrary.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_textlibrary.name
     *
     * @return the value of analysis_textlibrary.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_textlibrary.name
     *
     * @param name the value for analysis_textlibrary.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_textlibrary.describle
     *
     * @return the value of analysis_textlibrary.describle
     *
     * @mbg.generated
     */
    public String getDescrible() {
        return describle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_textlibrary.describle
     *
     * @param describle the value for analysis_textlibrary.describle
     *
     * @mbg.generated
     */
    public void setDescrible(String describle) {
        this.describle = describle == null ? null : describle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_textlibrary.fields
     *
     * @return the value of analysis_textlibrary.fields
     *
     * @mbg.generated
     */
    public String getFields() {
        return fields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_textlibrary.fields
     *
     * @param fields the value for analysis_textlibrary.fields
     *
     * @mbg.generated
     */
    public void setFields(String fields) {
        this.fields = fields == null ? null : fields.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_textlibrary.line_no
     *
     * @return the value of analysis_textlibrary.line_no
     *
     * @mbg.generated
     */
    public Long getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_textlibrary.line_no
     *
     * @param lineNo the value for analysis_textlibrary.line_no
     *
     * @mbg.generated
     */
    public void setLineNo(Long lineNo) {
        this.lineNo = lineNo;
    }

   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_textlibrary.filePath
     *
     * @return the value of analysis_textlibrary.filePath
     *
     * @mbg.generated
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_textlibrary.filePath
     *
     * @param filepath the value for analysis_textlibrary.filePath
     *
     * @mbg.generated
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_textlibrary.create_time
     *
     * @return the value of analysis_textlibrary.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_textlibrary.create_time
     *
     * @param createTime the value for analysis_textlibrary.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public Integer getImportStatus() {
		return importStatus;
	}

	public void setImportStatus(Integer importStatus) {
		this.importStatus = importStatus;
	}
    
    
}