package com.monetware.mapper.common;

import com.monetware.model.common.User;
import org.apache.ibatis.annotations.Param;

import java.sql.Timestamp;
import java.util.HashMap;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table br_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table br_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table br_user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table br_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table br_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table br_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    User getUserByName(@Param("username") String username);





    List<User> getUserList(HashMap<String, Object> queryMap);
    long getUserNo(@Param("userId")int userId,@Param("name")String name);
    long getMonthUserNo(@Param("userId")int userId,@Param("name")String name,@Param("firstDay") Timestamp firstDay);





}