package com.monetware.mapper.analysis;

import com.monetware.model.analysis.AnalysisProjectClassifyTraining;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.sql.Timestamp;
import java.util.List;
import java.util.Map;
@Repository
public interface AnalysisProjectClassifyTrainingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project_classify_training
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project_classify_training
     *
     * @mbg.generated
     */
    int insert(AnalysisProjectClassifyTraining record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project_classify_training
     *
     * @mbg.generated
     */
    int insertSelective(AnalysisProjectClassifyTraining record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project_classify_training
     *
     * @mbg.generated
     */
    AnalysisProjectClassifyTraining selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project_classify_training
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AnalysisProjectClassifyTraining record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project_classify_training
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AnalysisProjectClassifyTraining record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project_classify_training
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AnalysisProjectClassifyTraining record);

	List<AnalysisProjectClassifyTraining> getTrainingListByCategory(@Param("userId") int userId,
			@Param("category")String category);

	List<String> getCategories(@Param("name")String name,@Param("userId") int userId);

	long getThisMonthItems(@Param("name")String name, @Param("userId")int userId, @Param("firstDay")Timestamp firstDay);

	List<AnalysisProjectClassifyTraining> getTrainingByUser(@Param("userId")int userId);

	List<AnalysisProjectClassifyTraining> getTrainingListByCategories(
			@Param("userId") int userId, @Param("categoriesSql") String categoriesSql);
	
	
	List<Map<String, String>> getCategoriesByPage(@Param("name")String name,@Param("userId") int userId,@Param("pageStart") long pageStart,@Param("pageSize") long pageSize);

	int deleteTrainingByCategory(@Param("categoryName")String categoryName, @Param("userId") int userId);

	void updateCategoryName(@Param("oldCategoryName")String oldCategoryName,@Param("newCategoryName")String newCategoryName, @Param("userId")int userId);

	long getTrainingNoByCategory(@Param("userId")int userId, @Param("categoryName")String categoryName);

	List<AnalysisProjectClassifyTraining> getTrainingByPage(@Param("userId")int userId, @Param("categoryName")String categoryName,@Param("pageStart") long pageStart,@Param("pageSize") long pageSize);
	
	
	
}