package com.monetware.mapper.analysis;

import com.monetware.model.analysis.AnalysisProject;
import org.apache.ibatis.annotations.Param;

import java.sql.Timestamp;
import java.util.List;
import java.util.Map;

public interface AnalysisProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project
     *
     * @mbg.generated
     */
//    int insert(AnalysisProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project
     *
     * @mbg.generated
     */
    int insertSelective(AnalysisProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project
     *
     * @mbg.generated
     */
    AnalysisProject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AnalysisProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project
     *
     * @mbg.generated
     */
//    int updateByPrimaryKeyWithBLOBs(AnalysisProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_project
     *
     * @mbg.generated
     */
//    int updateByPrimaryKey(AnalysisProject record);
    
    
    List<AnalysisProject> getUserAnalysisProjects(Map<String, Object> queryMap);

    long getMonthProjectNo(@Param("name")String name, @Param("userId") int userId, @Param("firstDay")Timestamp firstDay);
    
    long getUserAnalysisProjectsNo(@Param("name")String name,@Param("userId")int userId);
}