package com.monetware.mapper.analysis;

import com.monetware.model.analysis.AnalysisProjectClassify;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface AnalysisProjectClassifyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analysis_project_classify_0
	 * @mbg.generated
	 */
	int insert(@Param("projectId")long projectId,@Param("categoryName")String categoryName,@Param("categoryId")int categoryId,@Param("textInfoId")long textInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analysis_project_classify_0
	 * @mbg.generated
	 */
	int insertSelective(AnalysisProjectClassify record);
	
	
	void createClassifyResultTable(@Param("analysisProjectId")long projectId);
	
	void dropClassifyResultTable(@Param("analysisProjectId")long projectId);

	List<Map<String, String>> getCategoriesByPage(@Param("analysisProjectId") long projectId,@Param("pageStart") long pageStart,@Param("pageSize") long pageSize);

	long getCategoriesNo(@Param("analysisProjectId")long projectId);
	
	
	List<Long> getInfoByCategory(@Param("analysisProjectId") long projectId,@Param("categoryName") String categoryName,@Param("pageStart") long pageStart,@Param("pageSize") long pageSize);
	
	long getInfoNoByCategory(@Param("analysisProjectId")long projectId,@Param("categoryName") String categoryName);
}