package com.monetware.mapper.analysis;

import com.monetware.model.analysis.AnalysisSentimeDictionary;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.sql.Timestamp;
import java.util.List;
@Repository
public interface AnalysisSentimeDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_dictionary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_dictionary
     *
     * @mbg.generated
     */
    int insert(AnalysisSentimeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_dictionary
     *
     * @mbg.generated
     */
    int insertSelective(AnalysisSentimeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_dictionary
     *
     * @mbg.generated
     */
    AnalysisSentimeDictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AnalysisSentimeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AnalysisSentimeDictionary record);


    List<AnalysisSentimeDictionary> getUserDictionaryByPage(@Param("name")String name , @Param("userId")int userId, @Param("pageStart")long pageStart, @Param("pageSize")long pageSize);


    long getUserDictionaryNo(@Param("name")String name,@Param("userId")int userId);

    long getThisMonthItems(@Param("name")String name, @Param("userId")int userId, @Param("firstDay")Timestamp firstDay);

    List<AnalysisSentimeDictionary> getUserAllDictionary(@Param("userId")int userId);

    long getDictioanryNoByName(@Param("name")String name,@Param("userId")int userId);

}