package com.monetware.mapper.analysis;


import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.monetware.model.analysis.AnalysisProjectCluste;
import com.monetware.model.analysis.TextLibrary;
@Repository
public interface AnalysisProjectClusteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analysis_project_cluste
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analysis_project_cluste
	 * @mbg.generated
	 */
	long insert(AnalysisProjectCluste projectCluste);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analysis_project_cluste
	 * @mbg.generated
	 */
	int insertSelective(AnalysisProjectCluste record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analysis_project_cluste
	 * @mbg.generated
	 */
	AnalysisProjectCluste selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analysis_project_cluste
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(AnalysisProjectCluste record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analysis_project_cluste
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(AnalysisProjectCluste record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analysis_project_cluste
	 * @mbg.generated
	 */
	int updateByPrimaryKey(AnalysisProjectCluste record);
	
	
	int deleteByProjectId(@Param("projectId") long projectId );
	
	
	List<AnalysisProjectCluste> getProjectCluste(Map<String, Long> queryMap);
	
	long getProjectClusteNo(@Param("projectId") long projectId);
	
	
	
}