package com.monetware.mapper.analysis;

import com.monetware.model.analysis.AnalysisSentimeWord;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface AnalysisSentimeWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_word
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_word
     *
     * @mbg.generated
     */
    int insert(AnalysisSentimeWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_word
     *
     * @mbg.generated
     */
    int insertSelective(AnalysisSentimeWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_word
     *
     * @mbg.generated
     */
    AnalysisSentimeWord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_word
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AnalysisSentimeWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_sentime_word
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AnalysisSentimeWord record);




    long getDictionaryWordsNo(@Param("dictionaryId")long dictionaryId, @Param("word")String word);

    List<AnalysisSentimeWord> getDictionaryWordsByPage(@Param("dictionaryId")long dictionaryId , @Param("word")String word, @Param("pageStart") long pageStart, @Param("pageSize") long pageSize);



    List<AnalysisSentimeWord> getDictionaryAllWords(@Param("dictionaryId")long dictionaryId);


    AnalysisSentimeWord selectByName(@Param("dictionaryId") Long dictionaryId,@Param("word")String name);


    int deleteByDictionaryId(@Param("dictionaryId")long dictionaryId);


}