package com.monetware.mapper.analysis;

import com.monetware.model.analysis.TextLibrary;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.sql.Timestamp;
import java.util.List;
import java.util.Map;
@Repository
public interface TextLibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_textlibrary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_textlibrary
     *
     * @mbg.generated
     */
    int insert(TextLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_textlibrary
     *
     * @mbg.generated
     */
    int insertSelective(TextLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_textlibrary
     *
     * @mbg.generated
     */
    TextLibrary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_textlibrary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TextLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis_textlibrary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TextLibrary record);
    
    
    List<TextLibrary> getUsertTextLibraries(Map<String, Object> queryMap);

    long getMonthTextLibraryNo(@Param("firstDay")Timestamp firstDay, @Param("userId")long userId, @Param("name")String name);

    List<TextLibrary> getUserAllTextLibraries(@Param("userId")int userId);

    long getUsertTextLibrariesNo(@Param("userId")int userId);
	
    TextLibrary getTextLibrary(@Param("id")long id);
    
    
}