package com.monetware.mapper.collect;

import com.monetware.model.collect.CollectLog;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.sql.Timestamp;
import java.util.List;
import java.util.Map;

@Repository
public interface CollectLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_log_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_log_1
     *
     * @mbg.generated
     */
    int insert(CollectLog record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_log_1
     *
     * @mbg.generated
     */
    CollectLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_log_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CollectLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_log_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CollectLog record);

    /**
     * 插入日志记录
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_log_1
     *
     * @mbg.generated
     */
    int insertSelective(@Param("projectId") long projectId,CollectLog record);

    int insertCollectLog(@Param("projectId")long projectId,@Param("level")String level,@Param("content")String content);
    //创建日志表
    int createCollectLogTable(@Param("projectId")long projectId);

    //删除日志表
    int dropCollectLogTable(@Param("projectId")long projectId);

    //分页查询日志
    List<CollectLog> getCollectLogs(@Param("projectId")long projectId,@Param("level") String level,@Param("pageStart") long pageStart,@Param("pageSize")long pageSize);

    //获取日志数量
    long getCollectLogNo(@Param("projectId")long projectId,@Param("level")String level);

    Timestamp getStartTime(@Param("projectId")long projectId);

    long getTimeNo(@Param("projectId")long projectId,@Param("startTime")long startTime,@Param("endTime")long endTime);
}